--
-- PostgreSQL database dump
--

\restrict Ya0LcVusSFuRMu5JYu0o4IYTW9oTmwRbouRc0Y6PgkXMBWFv8qVSXwfG7XRquvc

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-16 22:01:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 265 (class 1259 OID 17353)
-- Name: alerta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.alerta (
    idalerta integer NOT NULL,
    nino_curp character varying(18) NOT NULL,
    nino_rfc character varying(13) NOT NULL,
    tipo character varying(50),
    descripcion text,
    fechageneracion date,
    estado character varying(20)
);


ALTER TABLE public.alerta OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 17352)
-- Name: alerta_idalerta_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.alerta_idalerta_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.alerta_idalerta_seq OWNER TO postgres;

--
-- TOC entry 5351 (class 0 OID 0)
-- Dependencies: 264
-- Name: alerta_idalerta_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.alerta_idalerta_seq OWNED BY public.alerta.idalerta;


--
-- TOC entry 277 (class 1259 OID 17427)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 17426)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 279 (class 1259 OID 17435)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 278 (class 1259 OID 17434)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 17421)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 17420)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 281 (class 1259 OID 17441)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 283 (class 1259 OID 17449)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 282 (class 1259 OID 17448)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 17440)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 285 (class 1259 OID 17455)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 284 (class 1259 OID 17454)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17103)
-- Name: biologico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.biologico (
    idvacuna integer NOT NULL,
    nombre character varying(100) NOT NULL,
    dosisrequeridas integer,
    intervalodias integer,
    edadminimameses integer,
    edadmaximameses integer,
    restricciones text,
    idesquema integer
);


ALTER TABLE public.biologico OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17102)
-- Name: biologico_idvacuna_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.biologico_idvacuna_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.biologico_idvacuna_seq OWNER TO postgres;

--
-- TOC entry 5352 (class 0 OID 0)
-- Dependencies: 236
-- Name: biologico_idvacuna_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.biologico_idvacuna_seq OWNED BY public.biologico.idvacuna;


--
-- TOC entry 246 (class 1259 OID 17169)
-- Name: campaniavacunacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaniavacunacion (
    idcampania integer NOT NULL,
    nombre character varying(100) NOT NULL,
    fechainicio date,
    fechafin date,
    objetivo text,
    estado character varying(20),
    CONSTRAINT campaniavacunacion_estado_check CHECK (((estado)::text = ANY ((ARRAY['planificada'::character varying, 'activa'::character varying, 'finalizada'::character varying, 'cancelada'::character varying])::text[])))
);


ALTER TABLE public.campaniavacunacion OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17168)
-- Name: campaniavacunacion_idcampania_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.campaniavacunacion_idcampania_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.campaniavacunacion_idcampania_seq OWNER TO postgres;

--
-- TOC entry 5353 (class 0 OID 0)
-- Dependencies: 245
-- Name: campaniavacunacion_idcampania_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.campaniavacunacion_idcampania_seq OWNED BY public.campaniavacunacion.idcampania;


--
-- TOC entry 244 (class 1259 OID 17153)
-- Name: censonino; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.censonino (
    idcenso integer NOT NULL,
    nino_curp character varying(18) NOT NULL,
    nino_rfc character varying(13) NOT NULL
);


ALTER TABLE public.censonino OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17140)
-- Name: censonominal; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.censonominal (
    idcenso integer NOT NULL,
    idunidad integer,
    fechaactualizacion date,
    descripcion text
);


ALTER TABLE public.censonominal OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17139)
-- Name: censonominal_idcenso_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.censonominal_idcenso_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.censonominal_idcenso_seq OWNER TO postgres;

--
-- TOC entry 5354 (class 0 OID 0)
-- Dependencies: 242
-- Name: censonominal_idcenso_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.censonominal_idcenso_seq OWNED BY public.censonominal.idcenso;


--
-- TOC entry 226 (class 1259 OID 17000)
-- Name: colonia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.colonia (
    idcol integer NOT NULL,
    idmuni integer NOT NULL,
    nombre character varying(50) NOT NULL,
    cp character varying(10)
);


ALTER TABLE public.colonia OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16999)
-- Name: colonia_idcol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.colonia_idcol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.colonia_idcol_seq OWNER TO postgres;

--
-- TOC entry 5355 (class 0 OID 0)
-- Dependencies: 225
-- Name: colonia_idcol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.colonia_idcol_seq OWNED BY public.colonia.idcol;


--
-- TOC entry 259 (class 1259 OID 17292)
-- Name: detallepedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.detallepedido (
    iddetalle integer NOT NULL,
    idpedido integer NOT NULL,
    idvacuna integer NOT NULL,
    cantidadsolicitada integer NOT NULL
);


ALTER TABLE public.detallepedido OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 17291)
-- Name: detallepedido_iddetalle_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.detallepedido_iddetalle_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.detallepedido_iddetalle_seq OWNER TO postgres;

--
-- TOC entry 5356 (class 0 OID 0)
-- Dependencies: 258
-- Name: detallepedido_iddetalle_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.detallepedido_iddetalle_seq OWNED BY public.detallepedido.iddetalle;


--
-- TOC entry 228 (class 1259 OID 17012)
-- Name: direccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.direccion (
    iddireccion integer NOT NULL,
    idcol integer NOT NULL,
    calle character varying(100),
    numex character varying(10),
    numin character varying(10),
    ref text
);


ALTER TABLE public.direccion OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17011)
-- Name: direccion_iddireccion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.direccion_iddireccion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.direccion_iddireccion_seq OWNER TO postgres;

--
-- TOC entry 5357 (class 0 OID 0)
-- Dependencies: 227
-- Name: direccion_iddireccion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.direccion_iddireccion_seq OWNED BY public.direccion.iddireccion;


--
-- TOC entry 287 (class 1259 OID 17513)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 286 (class 1259 OID 17512)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 17413)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 17412)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 17405)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 17404)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 288 (class 1259 OID 17541)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 17233)
-- Name: enfermedad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enfermedad (
    idenferm integer NOT NULL,
    nombre character varying(100) NOT NULL,
    cientifico character varying(100),
    tipo_agente character varying(50),
    grupo character varying(50),
    transmision text,
    complicacion text,
    vacunas text
);


ALTER TABLE public.enfermedad OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 17232)
-- Name: enfermedad_idenferm_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.enfermedad_idenferm_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.enfermedad_idenferm_seq OWNER TO postgres;

--
-- TOC entry 5358 (class 0 OID 0)
-- Dependencies: 251
-- Name: enfermedad_idenferm_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.enfermedad_idenferm_seq OWNED BY public.enfermedad.idenferm;


--
-- TOC entry 231 (class 1259 OID 17055)
-- Name: enlacevacunacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enlacevacunacion (
    curp character varying(18) NOT NULL,
    rfc character varying(13) NOT NULL,
    foliocredencial character varying(20) NOT NULL,
    activo boolean DEFAULT true
);


ALTER TABLE public.enlacevacunacion OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17094)
-- Name: esquemavacunacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.esquemavacunacion (
    idesquema integer NOT NULL,
    nombre character varying(100) NOT NULL,
    descripcion text,
    edadminmeses integer,
    edadmaxmeses integer
);


ALTER TABLE public.esquemavacunacion OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17093)
-- Name: esquemavacunacion_idesquema_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.esquemavacunacion_idesquema_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.esquemavacunacion_idesquema_seq OWNER TO postgres;

--
-- TOC entry 5359 (class 0 OID 0)
-- Dependencies: 234
-- Name: esquemavacunacion_idesquema_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.esquemavacunacion_idesquema_seq OWNED BY public.esquemavacunacion.idesquema;


--
-- TOC entry 222 (class 1259 OID 16976)
-- Name: estado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.estado (
    idestado integer NOT NULL,
    idpais integer NOT NULL,
    nombre character varying(50) NOT NULL,
    abreviatura character varying(10)
);


ALTER TABLE public.estado OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16975)
-- Name: estado_idestado_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.estado_idestado_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.estado_idestado_seq OWNER TO postgres;

--
-- TOC entry 5360 (class 0 OID 0)
-- Dependencies: 221
-- Name: estado_idestado_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.estado_idestado_seq OWNED BY public.estado.idestado;


--
-- TOC entry 232 (class 1259 OID 17068)
-- Name: funcionariojurisdiccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funcionariojurisdiccion (
    curp character varying(18) NOT NULL,
    rfc character varying(13) NOT NULL,
    puesto character varying(100)
);


ALTER TABLE public.funcionariojurisdiccion OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 17257)
-- Name: inventariobiologicos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventariobiologicos (
    idinventario integer NOT NULL,
    idunidad integer,
    idvacuna integer,
    fecharegistro date,
    cantidaddisponible integer,
    cantidadaplicada integer,
    fechacaducidad date
);


ALTER TABLE public.inventariobiologicos OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 17256)
-- Name: inventariobiologicos_idinventario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inventariobiologicos_idinventario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inventariobiologicos_idinventario_seq OWNER TO postgres;

--
-- TOC entry 5361 (class 0 OID 0)
-- Dependencies: 254
-- Name: inventariobiologicos_idinventario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inventariobiologicos_idinventario_seq OWNED BY public.inventariobiologicos.idinventario;


--
-- TOC entry 239 (class 1259 OID 17117)
-- Name: jurisdiccionsanitaria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jurisdiccionsanitaria (
    idjurisdiccion integer NOT NULL,
    nombre character varying(100) NOT NULL,
    region character varying(100),
    direccion text,
    telefono character varying(20)
);


ALTER TABLE public.jurisdiccionsanitaria OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17116)
-- Name: jurisdiccionsanitaria_idjurisdiccion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.jurisdiccionsanitaria_idjurisdiccion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.jurisdiccionsanitaria_idjurisdiccion_seq OWNER TO postgres;

--
-- TOC entry 5362 (class 0 OID 0)
-- Dependencies: 238
-- Name: jurisdiccionsanitaria_idjurisdiccion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.jurisdiccionsanitaria_idjurisdiccion_seq OWNED BY public.jurisdiccionsanitaria.idjurisdiccion;


--
-- TOC entry 224 (class 1259 OID 16988)
-- Name: municipio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.municipio (
    idmuni integer NOT NULL,
    idestado integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.municipio OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 16987)
-- Name: municipio_idmuni_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.municipio_idmuni_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.municipio_idmuni_seq OWNER TO postgres;

--
-- TOC entry 5363 (class 0 OID 0)
-- Dependencies: 223
-- Name: municipio_idmuni_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.municipio_idmuni_seq OWNED BY public.municipio.idmuni;


--
-- TOC entry 233 (class 1259 OID 17078)
-- Name: nino; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nino (
    curp character varying(18) NOT NULL,
    rfc character varying(13) NOT NULL,
    tutor_curp character varying(18) NOT NULL,
    tutor_rfc character varying(13) NOT NULL
);


ALTER TABLE public.nino OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 17241)
-- Name: nino_enfermedad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.nino_enfermedad (
    nino_curp character varying(18) NOT NULL,
    nino_rfc character varying(13) NOT NULL,
    idenferm integer NOT NULL
);


ALTER TABLE public.nino_enfermedad OWNER TO postgres;

--
-- TOC entry 267 (class 1259 OID 17367)
-- Name: notificacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificacion (
    idnotificacion integer NOT NULL,
    tiporeferencia character varying(30),
    idreferencia integer NOT NULL,
    tutor_curp character varying(18),
    tutor_rfc character varying(13),
    enlace_curp character varying(18),
    enlace_rfc character varying(13),
    canal character varying(30),
    mensaje text,
    fechaenvio date,
    CONSTRAINT notificacion_canal_check CHECK (((canal)::text = ANY ((ARRAY['SMS'::character varying, 'WhatsApp'::character varying, 'correo'::character varying])::text[]))),
    CONSTRAINT notificacion_tiporeferencia_check CHECK (((tiporeferencia)::text = ANY ((ARRAY['alerta'::character varying, 'pedido'::character varying])::text[])))
);


ALTER TABLE public.notificacion OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 17366)
-- Name: notificacion_idnotificacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.notificacion_idnotificacion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.notificacion_idnotificacion_seq OWNER TO postgres;

--
-- TOC entry 5364 (class 0 OID 0)
-- Dependencies: 266
-- Name: notificacion_idnotificacion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.notificacion_idnotificacion_seq OWNED BY public.notificacion.idnotificacion;


--
-- TOC entry 220 (class 1259 OID 16969)
-- Name: pais; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pais (
    idpais integer NOT NULL,
    nombre character varying(50) NOT NULL
);


ALTER TABLE public.pais OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16968)
-- Name: pais_idpais_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pais_idpais_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pais_idpais_seq OWNER TO postgres;

--
-- TOC entry 5365 (class 0 OID 0)
-- Dependencies: 219
-- Name: pais_idpais_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pais_idpais_seq OWNED BY public.pais.idpais;


--
-- TOC entry 257 (class 1259 OID 17274)
-- Name: pedidobiologicos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pedidobiologicos (
    idpedido integer NOT NULL,
    idunidad integer,
    enlace_curp character varying(18) NOT NULL,
    enlace_rfc character varying(13) NOT NULL,
    fecha date,
    estado character varying(30),
    CONSTRAINT pedidobiologicos_estado_check CHECK (((estado)::text = ANY ((ARRAY['solicitado'::character varying, 'validacion_pendiente'::character varying, 'aprobado'::character varying, 'parcial'::character varying, 'en_espera'::character varying, 'rechazado'::character varying, 'surtido'::character varying, 'retirado'::character varying])::text[])))
);


ALTER TABLE public.pedidobiologicos OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 17273)
-- Name: pedidobiologicos_idpedido_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pedidobiologicos_idpedido_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pedidobiologicos_idpedido_seq OWNER TO postgres;

--
-- TOC entry 5366 (class 0 OID 0)
-- Dependencies: 256
-- Name: pedidobiologicos_idpedido_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pedidobiologicos_idpedido_seq OWNED BY public.pedidobiologicos.idpedido;


--
-- TOC entry 229 (class 1259 OID 17025)
-- Name: persona; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.persona (
    curp character varying(18) NOT NULL,
    rfc character varying(13) NOT NULL,
    nom character varying(50) NOT NULL,
    homocv character varying(5),
    app character varying(50),
    apm character varying(50),
    sexo character(1),
    tel character varying(20),
    correo character varying(100),
    fnac date,
    tsangre character varying(5),
    direc integer,
    rol integer DEFAULT 1 NOT NULL,
    CONSTRAINT persona_sexo_check CHECK ((sexo = ANY (ARRAY['H'::bpchar, 'M'::bpchar])))
);


ALTER TABLE public.persona OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 17179)
-- Name: puntovacunacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.puntovacunacion (
    idpunto integer NOT NULL,
    idcampania integer,
    nombre character varying(100),
    direccion text,
    horario character varying(50),
    responsable character varying(100)
);


ALTER TABLE public.puntovacunacion OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17178)
-- Name: puntovacunacion_idpunto_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.puntovacunacion_idpunto_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.puntovacunacion_idpunto_seq OWNER TO postgres;

--
-- TOC entry 5367 (class 0 OID 0)
-- Dependencies: 247
-- Name: puntovacunacion_idpunto_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.puntovacunacion_idpunto_seq OWNED BY public.puntovacunacion.idpunto;


--
-- TOC entry 250 (class 1259 OID 17193)
-- Name: registrovacunacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.registrovacunacion (
    idregistro integer NOT NULL,
    nino_curp character varying(18) NOT NULL,
    nino_rfc character varying(13) NOT NULL,
    idvacuna integer NOT NULL,
    personal_curp character varying(18) NOT NULL,
    personal_rfc character varying(13) NOT NULL,
    fecha date NOT NULL,
    dosis integer,
    observaciones text,
    estado character varying(20),
    idcampania integer,
    idpunto integer,
    idunidad integer,
    CONSTRAINT registrovacunacion_estado_check CHECK (((estado)::text = ANY ((ARRAY['aplicada'::character varying, 'pendiente'::character varying, 'atrasada'::character varying])::text[])))
);


ALTER TABLE public.registrovacunacion OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17192)
-- Name: registrovacunacion_idregistro_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.registrovacunacion_idregistro_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.registrovacunacion_idregistro_seq OWNER TO postgres;

--
-- TOC entry 5368 (class 0 OID 0)
-- Dependencies: 249
-- Name: registrovacunacion_idregistro_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.registrovacunacion_idregistro_seq OWNED BY public.registrovacunacion.idregistro;


--
-- TOC entry 269 (class 1259 OID 17388)
-- Name: reporte; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reporte (
    idreporte integer NOT NULL,
    idcampania integer,
    tipo character varying(50),
    fechageneracion date,
    totalvacunados integer,
    totalpendientes integer,
    cobertura numeric(5,2),
    contenido text
);


ALTER TABLE public.reporte OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 17387)
-- Name: reporte_idreporte_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.reporte_idreporte_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.reporte_idreporte_seq OWNER TO postgres;

--
-- TOC entry 5369 (class 0 OID 0)
-- Dependencies: 268
-- Name: reporte_idreporte_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.reporte_idreporte_seq OWNED BY public.reporte.idreporte;


--
-- TOC entry 263 (class 1259 OID 17329)
-- Name: retirogico; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.retirobiologico (
    idretiro integer NOT NULL,
    idpedido integer NOT NULL,
    enlace_curp character varying(18) NOT NULL,
    enlace_rfc character varying(13) NOT NULL,
    idjurisdiccion integer NOT NULL,
    fechahora timestamp without time zone,
    cantidadentregada integer,
    cadenafriook boolean,
    folio character varying(20),
    observaciones text
);
biolo

ALTER TABLE public.retirobiologico OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 17328)
-- Name: retirobiologico_idretiro_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.retirobiologico_idretiro_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.retirobiologico_idretiro_seq OWNER TO postgres;

--
-- TOC entry 5370 (class 0 OID 0)
-- Dependencies: 262
-- Name: retirobiologico_idretiro_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.retirobiologico_idretiro_seq OWNED BY public.retirobiologico.idretiro;


--
-- TOC entry 218 (class 1259 OID 16959)
-- Name: rol; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rol (
    idrol integer NOT NULL,
    nombre character varying(50) NOT NULL,
    detalles text,
    estado character varying(20),
    idespecialidad integer,
    CONSTRAINT rol_estado_check CHECK (((estado)::text = ANY ((ARRAY['habilitado'::character varying, 'inhabilitado'::character varying])::text[])))
);


ALTER TABLE public.rol OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16958)
-- Name: rol_idrol_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.rol_idrol_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rol_idrol_seq OWNER TO postgres;

--
-- TOC entry 5371 (class 0 OID 0)
-- Dependencies: 217
-- Name: rol_idrol_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.rol_idrol_seq OWNED BY public.rol.idrol;


--
-- TOC entry 241 (class 1259 OID 17126)
-- Name: unidaddesalud; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.unidaddesalud (
    idunidad integer NOT NULL,
    idjurisdiccion integer,
    nombre character varying(100) NOT NULL,
    municipio character varying(100),
    direccion text,
    telefono character varying(20)
);


ALTER TABLE public.unidaddesalud OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17125)
-- Name: unidaddesalud_idunidad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.unidaddesalud_idunidad_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.unidaddesalud_idunidad_seq OWNER TO postgres;

--
-- TOC entry 5372 (class 0 OID 0)
-- Dependencies: 240
-- Name: unidaddesalud_idunidad_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.unidaddesalud_idunidad_seq OWNED BY public.unidaddesalud.idunidad;


--
-- TOC entry 230 (class 1259 OID 17043)
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    curp character varying(18) NOT NULL,
    rfc character varying(13) NOT NULL,
    username character varying(50) NOT NULL,
    password character varying(255) NOT NULL,
    rol integer,
    idusuario integer NOT NULL
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- TOC entry 289 (class 1259 OID 17565)
-- Name: usuario_idusuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.usuario_idusuario_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.usuario_idusuario_seq OWNER TO postgres;

--
-- TOC entry 5373 (class 0 OID 0)
-- Dependencies: 289
-- Name: usuario_idusuario_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.usuario_idusuario_seq OWNED BY public.usuario.idusuario;


--
-- TOC entry 261 (class 1259 OID 17309)
-- Name: validacionpedido; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.validacionpedido (
    idvalidacion integer NOT NULL,
    idpedido integer NOT NULL,
    func_curp character varying(18) NOT NULL,
    func_rfc character varying(13) NOT NULL,
    fecha date,
    resultado character varying(20),
    comentario text,
    CONSTRAINT validacionpedido_resultado_check CHECK (((resultado)::text = ANY ((ARRAY['aprobado'::character varying, 'parcial'::character varying, 'en_espera'::character varying, 'rechazado'::character varying])::text[])))
);


ALTER TABLE public.validacionpedido OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 17308)
-- Name: validacionpedido_idvalidacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.validacionpedido_idvalidacion_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.validacionpedido_idvalidacion_seq OWNER TO postgres;

--
-- TOC entry 5374 (class 0 OID 0)
-- Dependencies: 260
-- Name: validacionpedido_idvalidacion_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.validacionpedido_idvalidacion_seq OWNED BY public.validacionpedido.idvalidacion;


--
-- TOC entry 4953 (class 2604 OID 17356)
-- Name: alerta idalerta; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerta ALTER COLUMN idalerta SET DEFAULT nextval('public.alerta_idalerta_seq'::regclass);


--
-- TOC entry 4940 (class 2604 OID 17106)
-- Name: biologico idvacuna; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.biologico ALTER COLUMN idvacuna SET DEFAULT nextval('public.biologico_idvacuna_seq'::regclass);


--
-- TOC entry 4944 (class 2604 OID 17172)
-- Name: campaniavacunacion idcampania; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaniavacunacion ALTER COLUMN idcampania SET DEFAULT nextval('public.campaniavacunacion_idcampania_seq'::regclass);


--
-- TOC entry 4943 (class 2604 OID 17143)
-- Name: censonominal idcenso; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonominal ALTER COLUMN idcenso SET DEFAULT nextval('public.censonominal_idcenso_seq'::regclass);


--
-- TOC entry 4934 (class 2604 OID 17003)
-- Name: colonia idcol; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colonia ALTER COLUMN idcol SET DEFAULT nextval('public.colonia_idcol_seq'::regclass);


--
-- TOC entry 4950 (class 2604 OID 17295)
-- Name: detallepedido iddetalle; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detallepedido ALTER COLUMN iddetalle SET DEFAULT nextval('public.detallepedido_iddetalle_seq'::regclass);


--
-- TOC entry 4935 (class 2604 OID 17015)
-- Name: direccion iddireccion; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion ALTER COLUMN iddireccion SET DEFAULT nextval('public.direccion_iddireccion_seq'::regclass);


--
-- TOC entry 4947 (class 2604 OID 17236)
-- Name: enfermedad idenferm; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enfermedad ALTER COLUMN idenferm SET DEFAULT nextval('public.enfermedad_idenferm_seq'::regclass);


--
-- TOC entry 4939 (class 2604 OID 17097)
-- Name: esquemavacunacion idesquema; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.esquemavacunacion ALTER COLUMN idesquema SET DEFAULT nextval('public.esquemavacunacion_idesquema_seq'::regclass);


--
-- TOC entry 4932 (class 2604 OID 16979)
-- Name: estado idestado; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado ALTER COLUMN idestado SET DEFAULT nextval('public.estado_idestado_seq'::regclass);


--
-- TOC entry 4948 (class 2604 OID 17260)
-- Name: inventariobiologicos idinventario; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventariobiologicos ALTER COLUMN idinventario SET DEFAULT nextval('public.inventariobiologicos_idinventario_seq'::regclass);


--
-- TOC entry 4941 (class 2604 OID 17120)
-- Name: jurisdiccionsanitaria idjurisdiccion; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurisdiccionsanitaria ALTER COLUMN idjurisdiccion SET DEFAULT nextval('public.jurisdiccionsanitaria_idjurisdiccion_seq'::regclass);


--
-- TOC entry 4933 (class 2604 OID 16991)
-- Name: municipio idmuni; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio ALTER COLUMN idmuni SET DEFAULT nextval('public.municipio_idmuni_seq'::regclass);


--
-- TOC entry 4954 (class 2604 OID 17370)
-- Name: notificacion idnotificacion; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion ALTER COLUMN idnotificacion SET DEFAULT nextval('public.notificacion_idnotificacion_seq'::regclass);


--
-- TOC entry 4931 (class 2604 OID 16972)
-- Name: pais idpais; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pais ALTER COLUMN idpais SET DEFAULT nextval('public.pais_idpais_seq'::regclass);


--
-- TOC entry 4949 (class 2604 OID 17277)
-- Name: pedidobiologicos idpedido; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidobiologicos ALTER COLUMN idpedido SET DEFAULT nextval('public.pedidobiologicos_idpedido_seq'::regclass);


--
-- TOC entry 4945 (class 2604 OID 17182)
-- Name: puntovacunacion idpunto; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puntovacunacion ALTER COLUMN idpunto SET DEFAULT nextval('public.puntovacunacion_idpunto_seq'::regclass);


--
-- TOC entry 4946 (class 2604 OID 17196)
-- Name: registrovacunacion idregistro; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion ALTER COLUMN idregistro SET DEFAULT nextval('public.registrovacunacion_idregistro_seq'::regclass);


--
-- TOC entry 4955 (class 2604 OID 17391)
-- Name: reporte idreporte; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte ALTER COLUMN idreporte SET DEFAULT nextval('public.reporte_idreporte_seq'::regclass);


--
-- TOC entry 4952 (class 2604 OID 17332)
-- Name: retirobiologico idretiro; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retirobiologico ALTER COLUMN idretiro SET DEFAULT nextval('public.retirobiologico_idretiro_seq'::regclass);


--
-- TOC entry 4930 (class 2604 OID 16962)
-- Name: rol idrol; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol ALTER COLUMN idrol SET DEFAULT nextval('public.rol_idrol_seq'::regclass);


--
-- TOC entry 4942 (class 2604 OID 17129)
-- Name: unidaddesalud idunidad; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidaddesalud ALTER COLUMN idunidad SET DEFAULT nextval('public.unidaddesalud_idunidad_seq'::regclass);


--
-- TOC entry 4937 (class 2604 OID 17566)
-- Name: usuario idusuario; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario ALTER COLUMN idusuario SET DEFAULT nextval('public.usuario_idusuario_seq'::regclass);


--
-- TOC entry 4951 (class 2604 OID 17312)
-- Name: validacionpedido idvalidacion; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.validacionpedido ALTER COLUMN idvalidacion SET DEFAULT nextval('public.validacionpedido_idvalidacion_seq'::regclass);


--
-- TOC entry 5321 (class 0 OID 17353)
-- Dependencies: 265
-- Data for Name: alerta; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.alerta (idalerta, nino_curp, nino_rfc, tipo, descripcion, fechageneracion, estado) FROM stdin;
\.


--
-- TOC entry 5333 (class 0 OID 17427)
-- Dependencies: 277
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
1	admin
2	enfermera
3	doctor
4	tutor
\.


--
-- TOC entry 5335 (class 0 OID 17435)
-- Dependencies: 279
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5331 (class 0 OID 17421)
-- Dependencies: 275
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add direccion	7	add_direccion
26	Can change direccion	7	change_direccion
27	Can delete direccion	7	delete_direccion
28	Can view direccion	7	view_direccion
29	Can add persona	8	add_persona
30	Can change persona	8	change_persona
31	Can delete persona	8	delete_persona
32	Can view persona	8	view_persona
33	Can add rol	9	add_rol
34	Can change rol	9	change_rol
35	Can delete rol	9	delete_rol
36	Can view rol	9	view_rol
37	Can add usuario	10	add_usuario
38	Can change usuario	10	change_usuario
39	Can delete usuario	10	delete_usuario
40	Can view usuario	10	view_usuario
\.


--
-- TOC entry 5337 (class 0 OID 17441)
-- Dependencies: 281
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$BRKOiEIAQiUJbJo4MVMAVi$KivbObW1o/bUk/faaA/yRMuqvZ4OdUkbFtDd+h681V0=	2025-10-10 14:03:46.928815-06	t	may			may10@gmail.com	t	t	2025-10-10 14:03:22.17458-06
2	pbkdf2_sha256$1000000$yuXtkEkg4AYR7p5Pawmker$2cs428O3aI5/rCFFmtNeDwiHDRlhxV4XYudqEgQrwU0=	\N	f	admin1			admin1@example.com	t	t	2025-10-10 20:39:25.167633-06
3	pbkdf2_sha256$1000000$5YlfxyOgGAF8zaYzLwGVLQ$QPZXoC8S7uI3w1IRmbIEpIe7hf9FmSlj+ztPrOZkMI8=	\N	f	enf1			enf1@example.com	f	t	2025-10-10 20:39:25.631005-06
4	pbkdf2_sha256$1000000$YtjkxPlAsrUHaQeoK1e1p3$LKjaG0jJxQPUYwfpzLrPC0Yf4u0tjz+eHGjf6o8X2bI=	\N	f	doc1			doc1@example.com	f	t	2025-10-10 20:39:25.992667-06
5	pbkdf2_sha256$1000000$zFcLMIayIZwHOiapPQtGxJ$l87kfnE1gQRWQg/AFPJgYIwuYZPwm/syFeP49FczHEM=	\N	f	tutor1			tutor1@example.com	f	t	2025-10-10 20:39:26.357469-06
6	pbkdf2_sha256$1000000$LwtQCxPI1tSxyX4csEc4mF$3NTLMBD9ppjNvAXsIpbVSikpPMdQucMTziQW2FwIyW8=	\N	t	root			root@example.com	t	t	2025-10-10 20:39:26.724897-06
\.


--
-- TOC entry 5339 (class 0 OID 17449)
-- Dependencies: 283
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
1	2	1
2	3	2
3	4	3
4	5	4
\.


--
-- TOC entry 5341 (class 0 OID 17455)
-- Dependencies: 285
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5293 (class 0 OID 17103)
-- Dependencies: 237
-- Data for Name: biologico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.biologico (idvacuna, nombre, dosisrequeridas, intervalodias, edadminimameses, edadmaximameses, restricciones, idesquema) FROM stdin;
\.


--
-- TOC entry 5302 (class 0 OID 17169)
-- Dependencies: 246
-- Data for Name: campaniavacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.campaniavacunacion (idcampania, nombre, fechainicio, fechafin, objetivo, estado) FROM stdin;
\.


--
-- TOC entry 5300 (class 0 OID 17153)
-- Dependencies: 244
-- Data for Name: censonino; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.censonino (idcenso, nino_curp, nino_rfc) FROM stdin;
\.


--
-- TOC entry 5299 (class 0 OID 17140)
-- Dependencies: 243
-- Data for Name: censonominal; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.censonominal (idcenso, idunidad, fechaactualizacion, descripcion) FROM stdin;
\.


--
-- TOC entry 5282 (class 0 OID 17000)
-- Dependencies: 226
-- Data for Name: colonia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.colonia (idcol, idmuni, nombre, cp) FROM stdin;
\.


--
-- TOC entry 5315 (class 0 OID 17292)
-- Dependencies: 259
-- Data for Name: detallepedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.detallepedido (iddetalle, idpedido, idvacuna, cantidadsolicitada) FROM stdin;
\.


--
-- TOC entry 5284 (class 0 OID 17012)
-- Dependencies: 228
-- Data for Name: direccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.direccion (iddireccion, idcol, calle, numex, numin, ref) FROM stdin;
\.


--
-- TOC entry 5343 (class 0 OID 17513)
-- Dependencies: 287
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- TOC entry 5329 (class 0 OID 17413)
-- Dependencies: 273
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	auth_app	direccion
8	auth_app	persona
9	auth_app	rol
10	auth_app	usuario
\.


--
-- TOC entry 5327 (class 0 OID 17405)
-- Dependencies: 271
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-08 23:10:54.935772-06
2	auth	0001_initial	2025-10-08 23:10:54.983174-06
3	admin	0001_initial	2025-10-08 23:10:54.994782-06
4	admin	0002_logentry_remove_auto_add	2025-10-08 23:10:54.999652-06
5	admin	0003_logentry_add_action_flag_choices	2025-10-08 23:10:55.005434-06
6	contenttypes	0002_remove_content_type_name	2025-10-08 23:10:55.016764-06
7	auth	0002_alter_permission_name_max_length	2025-10-08 23:10:55.022226-06
8	auth	0003_alter_user_email_max_length	2025-10-08 23:10:55.027154-06
9	auth	0004_alter_user_username_opts	2025-10-08 23:10:55.03246-06
10	auth	0005_alter_user_last_login_null	2025-10-08 23:10:55.037885-06
11	auth	0006_require_contenttypes_0002	2025-10-08 23:10:55.039352-06
12	auth	0007_alter_validators_add_error_messages	2025-10-08 23:10:55.044474-06
13	auth	0008_alter_user_username_max_length	2025-10-08 23:10:55.056089-06
14	auth	0009_alter_user_last_name_max_length	2025-10-08 23:10:55.062474-06
15	auth	0010_alter_group_name_max_length	2025-10-08 23:10:55.067936-06
16	auth	0011_update_proxy_permissions	2025-10-08 23:10:55.072258-06
17	auth	0012_alter_user_first_name_max_length	2025-10-08 23:10:55.077238-06
18	sessions	0001_initial	2025-10-08 23:10:55.086603-06
19	auth_app	0001_initial	2025-10-11 18:21:49.696457-06
20	auth_app	0002_add_rol_to_persona	2025-10-11 19:29:05.507689-06
\.


--
-- TOC entry 5344 (class 0 OID 17541)
-- Dependencies: 288
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
dyici8cwixjy2tfqa2zbkax2jppjyugb	.eJxVjEEOwiAQRe_C2hDawgAu3XsGwjCDVA0kpV0Z765NutDtf-_9lwhxW0vYOi9hJnEWgzj9bhjTg-sO6B7rrcnU6rrMKHdFHrTLayN-Xg7376DEXr61hxFYmWT9kK3JGZg0RR41ojKaUHnnwLoM3oDVduKJOSmVGDOyi1q8P-MmOFI:1v7JL8:9F11ye7BMTHdpdOdvFY6SSXO4iD8l4NJWcCLjS0fTqU	2025-10-24 14:03:46.933459-06
\.


--
-- TOC entry 5308 (class 0 OID 17233)
-- Dependencies: 252
-- Data for Name: enfermedad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enfermedad (idenferm, nombre, cientifico, tipo_agente, grupo, transmision, complicacion, vacunas) FROM stdin;
\.


--
-- TOC entry 5287 (class 0 OID 17055)
-- Dependencies: 231
-- Data for Name: enlacevacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enlacevacunacion (curp, rfc, foliocredencial, activo) FROM stdin;
\.


--
-- TOC entry 5291 (class 0 OID 17094)
-- Dependencies: 235
-- Data for Name: esquemavacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.esquemavacunacion (idesquema, nombre, descripcion, edadminmeses, edadmaxmeses) FROM stdin;
\.


--
-- TOC entry 5278 (class 0 OID 16976)
-- Dependencies: 222
-- Data for Name: estado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.estado (idestado, idpais, nombre, abreviatura) FROM stdin;
\.


--
-- TOC entry 5288 (class 0 OID 17068)
-- Dependencies: 232
-- Data for Name: funcionariojurisdiccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.funcionariojurisdiccion (curp, rfc, puesto) FROM stdin;
\.


--
-- TOC entry 5311 (class 0 OID 17257)
-- Dependencies: 255
-- Data for Name: inventariobiologicos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventariobiologicos (idinventario, idunidad, idvacuna, fecharegistro, cantidaddisponible, cantidadaplicada, fechacaducidad) FROM stdin;
\.


--
-- TOC entry 5295 (class 0 OID 17117)
-- Dependencies: 239
-- Data for Name: jurisdiccionsanitaria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.jurisdiccionsanitaria (idjurisdiccion, nombre, region, direccion, telefono) FROM stdin;
\.


--
-- TOC entry 5280 (class 0 OID 16988)
-- Dependencies: 224
-- Data for Name: municipio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.municipio (idmuni, idestado, nombre) FROM stdin;
\.


--
-- TOC entry 5289 (class 0 OID 17078)
-- Dependencies: 233
-- Data for Name: nino; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nino (curp, rfc, tutor_curp, tutor_rfc) FROM stdin;
\.


--
-- TOC entry 5309 (class 0 OID 17241)
-- Dependencies: 253
-- Data for Name: nino_enfermedad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.nino_enfermedad (nino_curp, nino_rfc, idenferm) FROM stdin;
\.


--
-- TOC entry 5323 (class 0 OID 17367)
-- Dependencies: 267
-- Data for Name: notificacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificacion (idnotificacion, tiporeferencia, idreferencia, tutor_curp, tutor_rfc, enlace_curp, enlace_rfc, canal, mensaje, fechaenvio) FROM stdin;
\.


--
-- TOC entry 5276 (class 0 OID 16969)
-- Dependencies: 220
-- Data for Name: pais; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pais (idpais, nombre) FROM stdin;
\.


--
-- TOC entry 5313 (class 0 OID 17274)
-- Dependencies: 257
-- Data for Name: pedidobiologicos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pedidobiologicos (idpedido, idunidad, enlace_curp, enlace_rfc, fecha, estado) FROM stdin;
\.


--
-- TOC entry 5285 (class 0 OID 17025)
-- Dependencies: 229
-- Data for Name: persona; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.persona (curp, rfc, nom, homocv, app, apm, sexo, tel, correo, fnac, tsangre, direc, rol) FROM stdin;
MARA030910HTCYYNA6	MARA030910	jose angel	\N	may	reyes	H	363898356	angelmay41383@gmail.com	2025-10-15	o+	\N	1
JANDS132	JANDS132	Instituto	\N	macuspana	Tabasco	H	9876543210	tec@gmail.com	2025-10-20	RH-	\N	1
NSADSA123A3	NSADSA123A	Instituto	\N	macuspana	Tabasco	H	7986543210	tec123@gmail.com	2025-10-14	a+	\N	1
NSADSA123A3ADSASD	NSADSA123A	InstiT	\N	macuspI	TabasL	H	123405679	macus@gmail.com	2025-10-14	a+	\N	1
MARA1947YH57	MARA1947YH	angel	\N	reyes	may	H	9389532014	maiz@gmail.com	2025-10-20	o+	\N	1
SDUHI13238UISDW	SDUHI13238	jose	\N	magaña	sosa	M	938956201	josue@gmail.com	2025-10-15	A+	\N	2
tfygvubhu652	tfygvubhu6	jennifer	\N	may	reyes	M	231654897	jeni@gamil.com	2025-10-03	RH-	\N	3
\.


--
-- TOC entry 5304 (class 0 OID 17179)
-- Dependencies: 248
-- Data for Name: puntovacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.puntovacunacion (idpunto, idcampania, nombre, direccion, horario, responsable) FROM stdin;
\.


--
-- TOC entry 5306 (class 0 OID 17193)
-- Dependencies: 250
-- Data for Name: registrovacunacion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.registrovacunacion (idregistro, nino_curp, nino_rfc, idvacuna, personal_curp, personal_rfc, fecha, dosis, observaciones, estado, idcampania, idpunto, idunidad) FROM stdin;
\.


--
-- TOC entry 5325 (class 0 OID 17388)
-- Dependencies: 269
-- Data for Name: reporte; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reporte (idreporte, idcampania, tipo, fechageneracion, totalvacunados, totalpendientes, cobertura, contenido) FROM stdin;
\.


--
-- TOC entry 5319 (class 0 OID 17329)
-- Dependencies: 263
-- Data for Name: retirobiologico; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.retirobiologico (idretiro, idpedido, enlace_curp, enlace_rfc, idjurisdiccion, fechahora, cantidadentregada, cadenafriook, folio, observaciones) FROM stdin;
\.


--
-- TOC entry 5274 (class 0 OID 16959)
-- Dependencies: 218
-- Data for Name: rol; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rol (idrol, nombre, detalles, estado, idespecialidad) FROM stdin;
1	Administrador	Usuario con acceso total al sistema	habilitado	\N
2	Doctor	Profesional encargado del registro y control médico	habilitado	\N
3	Enfermera	Personal auxiliar con funciones de vacunación	habilitado	\N
4	Tutor	Padre o tutor responsable del menor vacunado	habilitado	\N
\.


--
-- TOC entry 5297 (class 0 OID 17126)
-- Dependencies: 241
-- Data for Name: unidaddesalud; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.unidaddesalud (idunidad, idjurisdiccion, nombre, municipio, direccion, telefono) FROM stdin;
\.


--
-- TOC entry 5286 (class 0 OID 17043)
-- Dependencies: 230
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuario (curp, rfc, username, password, rol, idusuario) FROM stdin;
MARA030910HTCYYNA6	MARA030910	may	pbkdf2_sha256$1000000$4NA8DnuGVcyerAyI1X0sKX$xMIq5q/u7kPG4O1Kc4AThGl/0hEKnb0RUmUitzJSNxk=	1	1
JANDS132	JANDS132	itsm	pbkdf2_sha256$1000000$VdOveBJIreaM7huTMSWX2L$IXdZxHJ3yMrNCZvHQ/oUiImIf9iPQALtFyacrVAz5YM=	1	2
NSADSA123A3ADSASD	NSADSA123A	macus	pbkdf2_sha256$1000000$go7mQHaIJnVQKYhz0R2s6Z$rEJRlHcD8Ce47lqipjid366nx54/SXBS+gtqGd660Cw=	1	4
MARA1947YH57	MARA1947YH	angel	pbkdf2_sha256$1000000$XCRsYqjwJYX85hcDNUeOvs$/sRzAdayftgApBmqbeJMtIp0CyD0BxLdPSnulutgwE8=	1	5
SDUHI13238UISDW	SDUHI13238	josue	pbkdf2_sha256$1000000$Xhn6S2SlSN6qDXuK0708xJ$/N+asjIdi51m/veFBuag4C6ZPOjfTQlnwV/OL25Sjtw=	2	6
tfygvubhu652	tfygvubhu6	jenni	pbkdf2_sha256$1000000$Bo1DDLQSPzSrKwkIfuUmEP$pLcRUXa6B1Rnf/LKDsCx5Qj3Gzgz1Lnng2FbFzQp+Do=	3	7
\.


--
-- TOC entry 5317 (class 0 OID 17309)
-- Dependencies: 261
-- Data for Name: validacionpedido; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.validacionpedido (idvalidacion, idpedido, func_curp, func_rfc, fecha, resultado, comentario) FROM stdin;
\.


--
-- TOC entry 5375 (class 0 OID 0)
-- Dependencies: 264
-- Name: alerta_idalerta_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.alerta_idalerta_seq', 1, false);


--
-- TOC entry 5376 (class 0 OID 0)
-- Dependencies: 276
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 4, true);


--
-- TOC entry 5377 (class 0 OID 0)
-- Dependencies: 278
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5378 (class 0 OID 0)
-- Dependencies: 274
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 40, true);


--
-- TOC entry 5379 (class 0 OID 0)
-- Dependencies: 282
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 4, true);


--
-- TOC entry 5380 (class 0 OID 0)
-- Dependencies: 280
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 6, true);


--
-- TOC entry 5381 (class 0 OID 0)
-- Dependencies: 284
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5382 (class 0 OID 0)
-- Dependencies: 236
-- Name: biologico_idvacuna_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.biologico_idvacuna_seq', 1, false);


--
-- TOC entry 5383 (class 0 OID 0)
-- Dependencies: 245
-- Name: campaniavacunacion_idcampania_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.campaniavacunacion_idcampania_seq', 1, false);


--
-- TOC entry 5384 (class 0 OID 0)
-- Dependencies: 242
-- Name: censonominal_idcenso_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.censonominal_idcenso_seq', 1, false);


--
-- TOC entry 5385 (class 0 OID 0)
-- Dependencies: 225
-- Name: colonia_idcol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.colonia_idcol_seq', 1, false);


--
-- TOC entry 5386 (class 0 OID 0)
-- Dependencies: 258
-- Name: detallepedido_iddetalle_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.detallepedido_iddetalle_seq', 1, false);


--
-- TOC entry 5387 (class 0 OID 0)
-- Dependencies: 227
-- Name: direccion_iddireccion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.direccion_iddireccion_seq', 1, false);


--
-- TOC entry 5388 (class 0 OID 0)
-- Dependencies: 286
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- TOC entry 5389 (class 0 OID 0)
-- Dependencies: 272
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 10, true);


--
-- TOC entry 5390 (class 0 OID 0)
-- Dependencies: 270
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- TOC entry 5391 (class 0 OID 0)
-- Dependencies: 251
-- Name: enfermedad_idenferm_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enfermedad_idenferm_seq', 1, false);


--
-- TOC entry 5392 (class 0 OID 0)
-- Dependencies: 234
-- Name: esquemavacunacion_idesquema_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.esquemavacunacion_idesquema_seq', 1, false);


--
-- TOC entry 5393 (class 0 OID 0)
-- Dependencies: 221
-- Name: estado_idestado_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.estado_idestado_seq', 1, false);


--
-- TOC entry 5394 (class 0 OID 0)
-- Dependencies: 254
-- Name: inventariobiologicos_idinventario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventariobiologicos_idinventario_seq', 1, false);


--
-- TOC entry 5395 (class 0 OID 0)
-- Dependencies: 238
-- Name: jurisdiccionsanitaria_idjurisdiccion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jurisdiccionsanitaria_idjurisdiccion_seq', 1, false);


--
-- TOC entry 5396 (class 0 OID 0)
-- Dependencies: 223
-- Name: municipio_idmuni_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.municipio_idmuni_seq', 1, false);


--
-- TOC entry 5397 (class 0 OID 0)
-- Dependencies: 266
-- Name: notificacion_idnotificacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificacion_idnotificacion_seq', 1, false);


--
-- TOC entry 5398 (class 0 OID 0)
-- Dependencies: 219
-- Name: pais_idpais_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pais_idpais_seq', 1, false);


--
-- TOC entry 5399 (class 0 OID 0)
-- Dependencies: 256
-- Name: pedidobiologicos_idpedido_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pedidobiologicos_idpedido_seq', 1, false);


--
-- TOC entry 5400 (class 0 OID 0)
-- Dependencies: 247
-- Name: puntovacunacion_idpunto_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.puntovacunacion_idpunto_seq', 1, false);


--
-- TOC entry 5401 (class 0 OID 0)
-- Dependencies: 249
-- Name: registrovacunacion_idregistro_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.registrovacunacion_idregistro_seq', 1, false);


--
-- TOC entry 5402 (class 0 OID 0)
-- Dependencies: 268
-- Name: reporte_idreporte_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reporte_idreporte_seq', 1, false);


--
-- TOC entry 5403 (class 0 OID 0)
-- Dependencies: 262
-- Name: retirobiologico_idretiro_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.retirobiologico_idretiro_seq', 1, false);


--
-- TOC entry 5404 (class 0 OID 0)
-- Dependencies: 217
-- Name: rol_idrol_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rol_idrol_seq', 4, true);


--
-- TOC entry 5405 (class 0 OID 0)
-- Dependencies: 240
-- Name: unidaddesalud_idunidad_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.unidaddesalud_idunidad_seq', 1, false);


--
-- TOC entry 5406 (class 0 OID 0)
-- Dependencies: 289
-- Name: usuario_idusuario_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuario_idusuario_seq', 7, true);


--
-- TOC entry 5407 (class 0 OID 0)
-- Dependencies: 260
-- Name: validacionpedido_idvalidacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.validacionpedido_idvalidacion_seq', 1, false);


--
-- TOC entry 5026 (class 2606 OID 17360)
-- Name: alerta alerta_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerta
    ADD CONSTRAINT alerta_pkey PRIMARY KEY (idalerta);


--
-- TOC entry 5044 (class 2606 OID 17539)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5049 (class 2606 OID 17470)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5052 (class 2606 OID 17439)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5046 (class 2606 OID 17431)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5039 (class 2606 OID 17461)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5041 (class 2606 OID 17425)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 5060 (class 2606 OID 17453)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5063 (class 2606 OID 17485)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5054 (class 2606 OID 17445)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5066 (class 2606 OID 17459)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5069 (class 2606 OID 17499)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5057 (class 2606 OID 17534)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4996 (class 2606 OID 17110)
-- Name: biologico biologico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.biologico
    ADD CONSTRAINT biologico_pkey PRIMARY KEY (idvacuna);


--
-- TOC entry 5006 (class 2606 OID 17177)
-- Name: campaniavacunacion campaniavacunacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaniavacunacion
    ADD CONSTRAINT campaniavacunacion_pkey PRIMARY KEY (idcampania);


--
-- TOC entry 5004 (class 2606 OID 17157)
-- Name: censonino censonino_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonino
    ADD CONSTRAINT censonino_pkey PRIMARY KEY (idcenso, nino_curp, nino_rfc);


--
-- TOC entry 5002 (class 2606 OID 17147)
-- Name: censonominal censonominal_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonominal
    ADD CONSTRAINT censonominal_pkey PRIMARY KEY (idcenso);


--
-- TOC entry 4974 (class 2606 OID 17005)
-- Name: colonia colonia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colonia
    ADD CONSTRAINT colonia_pkey PRIMARY KEY (idcol);


--
-- TOC entry 5020 (class 2606 OID 17297)
-- Name: detallepedido detallepedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detallepedido
    ADD CONSTRAINT detallepedido_pkey PRIMARY KEY (iddetalle);


--
-- TOC entry 4976 (class 2606 OID 17019)
-- Name: direccion direccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_pkey PRIMARY KEY (iddireccion);


--
-- TOC entry 5072 (class 2606 OID 17520)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5034 (class 2606 OID 17419)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5036 (class 2606 OID 17417)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5032 (class 2606 OID 17411)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5076 (class 2606 OID 17547)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5012 (class 2606 OID 17240)
-- Name: enfermedad enfermedad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enfermedad
    ADD CONSTRAINT enfermedad_pkey PRIMARY KEY (idenferm);


--
-- TOC entry 4986 (class 2606 OID 17062)
-- Name: enlacevacunacion enlacevacunacion_foliocredencial_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enlacevacunacion
    ADD CONSTRAINT enlacevacunacion_foliocredencial_key UNIQUE (foliocredencial);


--
-- TOC entry 4988 (class 2606 OID 17060)
-- Name: enlacevacunacion enlacevacunacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enlacevacunacion
    ADD CONSTRAINT enlacevacunacion_pkey PRIMARY KEY (curp, rfc);


--
-- TOC entry 4994 (class 2606 OID 17101)
-- Name: esquemavacunacion esquemavacunacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.esquemavacunacion
    ADD CONSTRAINT esquemavacunacion_pkey PRIMARY KEY (idesquema);


--
-- TOC entry 4970 (class 2606 OID 16981)
-- Name: estado estado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_pkey PRIMARY KEY (idestado);


--
-- TOC entry 4990 (class 2606 OID 17072)
-- Name: funcionariojurisdiccion funcionariojurisdiccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionariojurisdiccion
    ADD CONSTRAINT funcionariojurisdiccion_pkey PRIMARY KEY (curp, rfc);


--
-- TOC entry 5016 (class 2606 OID 17262)
-- Name: inventariobiologicos inventariobiologicos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventariobiologicos
    ADD CONSTRAINT inventariobiologicos_pkey PRIMARY KEY (idinventario);


--
-- TOC entry 4998 (class 2606 OID 17124)
-- Name: jurisdiccionsanitaria jurisdiccionsanitaria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jurisdiccionsanitaria
    ADD CONSTRAINT jurisdiccionsanitaria_pkey PRIMARY KEY (idjurisdiccion);


--
-- TOC entry 4972 (class 2606 OID 16993)
-- Name: municipio municipio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_pkey PRIMARY KEY (idmuni);


--
-- TOC entry 5014 (class 2606 OID 17245)
-- Name: nino_enfermedad nino_enfermedad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino_enfermedad
    ADD CONSTRAINT nino_enfermedad_pkey PRIMARY KEY (nino_curp, nino_rfc, idenferm);


--
-- TOC entry 4992 (class 2606 OID 17082)
-- Name: nino nino_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_pkey PRIMARY KEY (curp, rfc);


--
-- TOC entry 5028 (class 2606 OID 17376)
-- Name: notificacion notificacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_pkey PRIMARY KEY (idnotificacion);


--
-- TOC entry 4968 (class 2606 OID 16974)
-- Name: pais pais_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pais
    ADD CONSTRAINT pais_pkey PRIMARY KEY (idpais);


--
-- TOC entry 5018 (class 2606 OID 17280)
-- Name: pedidobiologicos pedidobiologicos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidobiologicos
    ADD CONSTRAINT pedidobiologicos_pkey PRIMARY KEY (idpedido);


--
-- TOC entry 4978 (class 2606 OID 17032)
-- Name: persona persona_correo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_correo_key UNIQUE (correo);


--
-- TOC entry 4980 (class 2606 OID 17030)
-- Name: persona persona_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_pkey PRIMARY KEY (curp, rfc);


--
-- TOC entry 5008 (class 2606 OID 17186)
-- Name: puntovacunacion puntovacunacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puntovacunacion
    ADD CONSTRAINT puntovacunacion_pkey PRIMARY KEY (idpunto);


--
-- TOC entry 5010 (class 2606 OID 17201)
-- Name: registrovacunacion registrovacunacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_pkey PRIMARY KEY (idregistro);


--
-- TOC entry 5030 (class 2606 OID 17395)
-- Name: reporte reporte_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte
    ADD CONSTRAINT reporte_pkey PRIMARY KEY (idreporte);


--
-- TOC entry 5024 (class 2606 OID 17336)
-- Name: retirobiologico retirobiologico_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retirobiologico
    ADD CONSTRAINT retirobiologico_pkey PRIMARY KEY (idretiro);


--
-- TOC entry 4966 (class 2606 OID 16967)
-- Name: rol rol_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rol
    ADD CONSTRAINT rol_pkey PRIMARY KEY (idrol);


--
-- TOC entry 5000 (class 2606 OID 17133)
-- Name: unidaddesalud unidaddesalud_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidaddesalud
    ADD CONSTRAINT unidaddesalud_pkey PRIMARY KEY (idunidad);


--
-- TOC entry 4982 (class 2606 OID 17568)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (idusuario);


--
-- TOC entry 4984 (class 2606 OID 17049)
-- Name: usuario usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_username_key UNIQUE (username);


--
-- TOC entry 5022 (class 2606 OID 17317)
-- Name: validacionpedido validacionpedido_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.validacionpedido
    ADD CONSTRAINT validacionpedido_pkey PRIMARY KEY (idvalidacion);


--
-- TOC entry 5042 (class 1259 OID 17540)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5047 (class 1259 OID 17481)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5050 (class 1259 OID 17482)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5037 (class 1259 OID 17467)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 5058 (class 1259 OID 17497)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 5061 (class 1259 OID 17496)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 5064 (class 1259 OID 17511)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5067 (class 1259 OID 17510)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 5055 (class 1259 OID 17535)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 5070 (class 1259 OID 17531)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5073 (class 1259 OID 17532)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5074 (class 1259 OID 17549)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5077 (class 1259 OID 17548)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5115 (class 2606 OID 17361)
-- Name: alerta alerta_nino_curp_nino_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.alerta
    ADD CONSTRAINT alerta_nino_curp_nino_rfc_fkey FOREIGN KEY (nino_curp, nino_rfc) REFERENCES public.nino(curp, rfc);


--
-- TOC entry 5120 (class 2606 OID 17476)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5121 (class 2606 OID 17471)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5119 (class 2606 OID 17462)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5122 (class 2606 OID 17491)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5123 (class 2606 OID 17486)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5124 (class 2606 OID 17505)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5125 (class 2606 OID 17500)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5090 (class 2606 OID 17111)
-- Name: biologico biologico_idesquema_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.biologico
    ADD CONSTRAINT biologico_idesquema_fkey FOREIGN KEY (idesquema) REFERENCES public.esquemavacunacion(idesquema);


--
-- TOC entry 5093 (class 2606 OID 17158)
-- Name: censonino censonino_idcenso_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonino
    ADD CONSTRAINT censonino_idcenso_fkey FOREIGN KEY (idcenso) REFERENCES public.censonominal(idcenso);


--
-- TOC entry 5094 (class 2606 OID 17163)
-- Name: censonino censonino_nino_curp_nino_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonino
    ADD CONSTRAINT censonino_nino_curp_nino_rfc_fkey FOREIGN KEY (nino_curp, nino_rfc) REFERENCES public.nino(curp, rfc);


--
-- TOC entry 5092 (class 2606 OID 17148)
-- Name: censonominal censonominal_idunidad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.censonominal
    ADD CONSTRAINT censonominal_idunidad_fkey FOREIGN KEY (idunidad) REFERENCES public.unidaddesalud(idunidad);


--
-- TOC entry 5080 (class 2606 OID 17006)
-- Name: colonia colonia_idmuni_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.colonia
    ADD CONSTRAINT colonia_idmuni_fkey FOREIGN KEY (idmuni) REFERENCES public.municipio(idmuni);


--
-- TOC entry 5108 (class 2606 OID 17298)
-- Name: detallepedido detallepedido_idpedido_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detallepedido
    ADD CONSTRAINT detallepedido_idpedido_fkey FOREIGN KEY (idpedido) REFERENCES public.pedidobiologicos(idpedido) ON DELETE CASCADE;


--
-- TOC entry 5109 (class 2606 OID 17303)
-- Name: detallepedido detallepedido_idvacuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.detallepedido
    ADD CONSTRAINT detallepedido_idvacuna_fkey FOREIGN KEY (idvacuna) REFERENCES public.biologico(idvacuna);


--
-- TOC entry 5081 (class 2606 OID 17020)
-- Name: direccion direccion_idcol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.direccion
    ADD CONSTRAINT direccion_idcol_fkey FOREIGN KEY (idcol) REFERENCES public.colonia(idcol);


--
-- TOC entry 5126 (class 2606 OID 17521)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5127 (class 2606 OID 17526)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 5086 (class 2606 OID 17063)
-- Name: enlacevacunacion enlacevacunacion_curp_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enlacevacunacion
    ADD CONSTRAINT enlacevacunacion_curp_rfc_fkey FOREIGN KEY (curp, rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5078 (class 2606 OID 16982)
-- Name: estado estado_idpais_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.estado
    ADD CONSTRAINT estado_idpais_fkey FOREIGN KEY (idpais) REFERENCES public.pais(idpais);


--
-- TOC entry 5087 (class 2606 OID 17073)
-- Name: funcionariojurisdiccion funcionariojurisdiccion_curp_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funcionariojurisdiccion
    ADD CONSTRAINT funcionariojurisdiccion_curp_rfc_fkey FOREIGN KEY (curp, rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5104 (class 2606 OID 17263)
-- Name: inventariobiologicos inventariobiologicos_idunidad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventariobiologicos
    ADD CONSTRAINT inventariobiologicos_idunidad_fkey FOREIGN KEY (idunidad) REFERENCES public.unidaddesalud(idunidad);


--
-- TOC entry 5105 (class 2606 OID 17268)
-- Name: inventariobiologicos inventariobiologicos_idvacuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventariobiologicos
    ADD CONSTRAINT inventariobiologicos_idvacuna_fkey FOREIGN KEY (idvacuna) REFERENCES public.biologico(idvacuna);


--
-- TOC entry 5079 (class 2606 OID 16994)
-- Name: municipio municipio_idestado_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.municipio
    ADD CONSTRAINT municipio_idestado_fkey FOREIGN KEY (idestado) REFERENCES public.estado(idestado);


--
-- TOC entry 5088 (class 2606 OID 17083)
-- Name: nino nino_curp_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_curp_rfc_fkey FOREIGN KEY (curp, rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5102 (class 2606 OID 17246)
-- Name: nino_enfermedad nino_enfermedad_idenferm_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino_enfermedad
    ADD CONSTRAINT nino_enfermedad_idenferm_fkey FOREIGN KEY (idenferm) REFERENCES public.enfermedad(idenferm);


--
-- TOC entry 5103 (class 2606 OID 17251)
-- Name: nino_enfermedad nino_enfermedad_nino_curp_nino_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino_enfermedad
    ADD CONSTRAINT nino_enfermedad_nino_curp_nino_rfc_fkey FOREIGN KEY (nino_curp, nino_rfc) REFERENCES public.nino(curp, rfc);


--
-- TOC entry 5089 (class 2606 OID 17088)
-- Name: nino nino_tutor_curp_tutor_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.nino
    ADD CONSTRAINT nino_tutor_curp_tutor_rfc_fkey FOREIGN KEY (tutor_curp, tutor_rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5116 (class 2606 OID 17382)
-- Name: notificacion notificacion_enlace_curp_enlace_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_enlace_curp_enlace_rfc_fkey FOREIGN KEY (enlace_curp, enlace_rfc) REFERENCES public.enlacevacunacion(curp, rfc);


--
-- TOC entry 5117 (class 2606 OID 17377)
-- Name: notificacion notificacion_tutor_curp_tutor_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificacion
    ADD CONSTRAINT notificacion_tutor_curp_tutor_rfc_fkey FOREIGN KEY (tutor_curp, tutor_rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5106 (class 2606 OID 17286)
-- Name: pedidobiologicos pedidobiologicos_enlace_curp_enlace_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidobiologicos
    ADD CONSTRAINT pedidobiologicos_enlace_curp_enlace_rfc_fkey FOREIGN KEY (enlace_curp, enlace_rfc) REFERENCES public.enlacevacunacion(curp, rfc);


--
-- TOC entry 5107 (class 2606 OID 17281)
-- Name: pedidobiologicos pedidobiologicos_idunidad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pedidobiologicos
    ADD CONSTRAINT pedidobiologicos_idunidad_fkey FOREIGN KEY (idunidad) REFERENCES public.unidaddesalud(idunidad);


--
-- TOC entry 5082 (class 2606 OID 17033)
-- Name: persona persona_direc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_direc_fkey FOREIGN KEY (direc) REFERENCES public.direccion(iddireccion);


--
-- TOC entry 5083 (class 2606 OID 17551)
-- Name: persona persona_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.persona
    ADD CONSTRAINT persona_rol_fkey FOREIGN KEY (rol) REFERENCES public.rol(idrol);


--
-- TOC entry 5095 (class 2606 OID 17187)
-- Name: puntovacunacion puntovacunacion_idcampania_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.puntovacunacion
    ADD CONSTRAINT puntovacunacion_idcampania_fkey FOREIGN KEY (idcampania) REFERENCES public.campaniavacunacion(idcampania);


--
-- TOC entry 5096 (class 2606 OID 17207)
-- Name: registrovacunacion registrovacunacion_idcampania_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_idcampania_fkey FOREIGN KEY (idcampania) REFERENCES public.campaniavacunacion(idcampania);


--
-- TOC entry 5097 (class 2606 OID 17212)
-- Name: registrovacunacion registrovacunacion_idpunto_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_idpunto_fkey FOREIGN KEY (idpunto) REFERENCES public.puntovacunacion(idpunto);


--
-- TOC entry 5098 (class 2606 OID 17217)
-- Name: registrovacunacion registrovacunacion_idunidad_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_idunidad_fkey FOREIGN KEY (idunidad) REFERENCES public.unidaddesalud(idunidad);


--
-- TOC entry 5099 (class 2606 OID 17202)
-- Name: registrovacunacion registrovacunacion_idvacuna_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_idvacuna_fkey FOREIGN KEY (idvacuna) REFERENCES public.biologico(idvacuna);


--
-- TOC entry 5100 (class 2606 OID 17222)
-- Name: registrovacunacion registrovacunacion_nino_curp_nino_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_nino_curp_nino_rfc_fkey FOREIGN KEY (nino_curp, nino_rfc) REFERENCES public.nino(curp, rfc);


--
-- TOC entry 5101 (class 2606 OID 17227)
-- Name: registrovacunacion registrovacunacion_personal_curp_personal_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.registrovacunacion
    ADD CONSTRAINT registrovacunacion_personal_curp_personal_rfc_fkey FOREIGN KEY (personal_curp, personal_rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5118 (class 2606 OID 17396)
-- Name: reporte reporte_idcampania_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reporte
    ADD CONSTRAINT reporte_idcampania_fkey FOREIGN KEY (idcampania) REFERENCES public.campaniavacunacion(idcampania);


--
-- TOC entry 5112 (class 2606 OID 17347)
-- Name: retirobiologico retirobiologico_enlace_curp_enlace_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retirobiologico
    ADD CONSTRAINT retirobiologico_enlace_curp_enlace_rfc_fkey FOREIGN KEY (enlace_curp, enlace_rfc) REFERENCES public.enlacevacunacion(curp, rfc);


--
-- TOC entry 5113 (class 2606 OID 17342)
-- Name: retirobiologico retirobiologico_idjurisdiccion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retirobiologico
    ADD CONSTRAINT retirobiologico_idjurisdiccion_fkey FOREIGN KEY (idjurisdiccion) REFERENCES public.jurisdiccionsanitaria(idjurisdiccion);


--
-- TOC entry 5114 (class 2606 OID 17337)
-- Name: retirobiologico retirobiologico_idpedido_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retirobiologico
    ADD CONSTRAINT retirobiologico_idpedido_fkey FOREIGN KEY (idpedido) REFERENCES public.pedidobiologicos(idpedido);


--
-- TOC entry 5091 (class 2606 OID 17134)
-- Name: unidaddesalud unidaddesalud_idjurisdiccion_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.unidaddesalud
    ADD CONSTRAINT unidaddesalud_idjurisdiccion_fkey FOREIGN KEY (idjurisdiccion) REFERENCES public.jurisdiccionsanitaria(idjurisdiccion);


--
-- TOC entry 5084 (class 2606 OID 17050)
-- Name: usuario usuario_curp_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_curp_rfc_fkey FOREIGN KEY (curp, rfc) REFERENCES public.persona(curp, rfc);


--
-- TOC entry 5085 (class 2606 OID 17556)
-- Name: usuario usuario_rol_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_rol_fkey FOREIGN KEY (rol) REFERENCES public.rol(idrol);


--
-- TOC entry 5110 (class 2606 OID 17323)
-- Name: validacionpedido validacionpedido_func_curp_func_rfc_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.validacionpedido
    ADD CONSTRAINT validacionpedido_func_curp_func_rfc_fkey FOREIGN KEY (func_curp, func_rfc) REFERENCES public.funcionariojurisdiccion(curp, rfc);


--
-- TOC entry 5111 (class 2606 OID 17318)
-- Name: validacionpedido validacionpedido_idpedido_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.validacionpedido
    ADD CONSTRAINT validacionpedido_idpedido_fkey FOREIGN KEY (idpedido) REFERENCES public.pedidobiologicos(idpedido);


-- Completed on 2025-10-16 22:01:00

--
-- PostgreSQL database dump complete
--

\unrestrict Ya0LcVusSFuRMu5JYu0o4IYTW9oTmwRbouRc0Y6PgkXMBWFv8qVSXwfG7XRquvc

