# Generated by Django 5.2.7 on 2025-10-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('habilitado', 'Habilitado'), ('inhabilitado', 'Inhabilitado')], max_length=20)),
                ('idespecialidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=13)),
                ('nom', models.CharField(max_length=50)),
                ('homocv', models.CharField(blank=True, max_length=5, null=True)),
                ('app', models.CharField(blank=True, max_length=50, null=True)),
                ('apm', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('fnac', models.DateField(blank=True, null=True)),
                ('tsangre', models.CharField(blank=True, max_length=5, null=True)),
                ('direc', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, to='auth_app.rol')),
            ],
            options={
                'db_table': 'persona',
                'unique_together': {('curp', 'rfc')},
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('curp', models.CharField(max_length=18)),
                ('rfc', models.CharField(max_length=13)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, to='auth_app.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
                'unique_together': {('curp', 'rfc')},
            },
        ),
    ]
