# Generated by Django 5.2.7 on 2025-10-20 16:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biologico',
            fields=[
                ('idbiologico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('cantidad_total', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cantidad_disponible', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'biologico',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('idalmacen', models.AutoField(primary_key=True, serialize=False)),
                ('idunidad', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('general', 'General'), ('unidad', 'Unidad')], max_length=30)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('biologico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='biologicos_app.biologico')),
            ],
            options={
                'db_table': 'almacen',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
