# Generated by Django 5.2.7 on 2025-10-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoVacunacion',
            fields=[
                ('idpunto', models.AutoField(primary_key=True, serialize=False)),
                ('idcampania', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('horario', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('idvacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('dosis_requeridas', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva')], default='activa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroVacunacion',
            fields=[
                ('idregistro', models.AutoField(primary_key=True, serialize=False)),
                ('nino_curp', models.CharField(max_length=18)),
                ('nino_rfc', models.CharField(max_length=13)),
                ('personal_curp', models.CharField(max_length=18)),
                ('personal_rfc', models.CharField(max_length=13)),
                ('fecha', models.DateField()),
                ('dosis', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('aplicada', 'Aplicada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada')], default='pendiente', max_length=20)),
                ('idcampania', models.IntegerField(blank=True, null=True)),
                ('idunidad', models.IntegerField(blank=True, null=True)),
                ('idpunto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas_app.puntovacunacion')),
                ('idvacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='vacunas_app.vacuna')),
            ],
        ),
    ]
