# Generated by Django 5.2.7 on 2025-10-20 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='vacuna',
            name='idvacuna',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='intervalo_dosis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacunacion',
            name='dosis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registrovacunacion',
            name='estado',
            field=models.CharField(choices=[('aplicada', 'Aplicada'), ('pendiente', 'Pendiente'), ('atrasada', 'Atrasada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='registrovacunacion',
            name='idpunto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrovacunacion',
            name='idvacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas_app.vacuna'),
        ),
    ]
